BASE_URL = "https://tobeto.com/giris"
SIGN_UP_URL = "https://tobeto.com/sifremi-unuttum"
FIRST_LOGIN_BUTTON = ".border-light"
EMAIL_NAME = "email"
PASSWORD_NAME = "password"
LOGIN_BUTTON_XPATH = "//button[@class='btn btn-primary w-100 mt-6']"
LOGIN_MESSAGE_CSS = "div[class='toast-body']"
LOGIN_MESSAGE_CSS = "div[class='toast-body']"
SYSTEM_ERROR_MESSAGE_XPATH = "//*[@id='__next']/div/main/div[2]/div/div[2]"
ERROR_MESSAGE_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/form/p"
SIGN_UP_MAIL_XPATH = "//*[@id='__next']/div/main/section/div/div/div/input"
SEND_BUTTON_XPATH = "//*[@id='__next']/div/main/section/div/div/div/button"
SYSTEM_MESSAGE_XPATH = "//*[@id='__next']/div/main/div[2]/div/div[2]"
ERROR_SYSTEM_MESSAGE_XPATH = "//*[@id='__next']/div/main/div[2]/div/div[2]"
SYSTEM_SUCCESSFUL_MESSAGE_XPATH = "//*[@id='__next']/div/div[2]/div/div[2]"
REGISTER_URL = "https://tobeto.com/kayit-ol"
REGISTER_FIRST_NAME_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[1]"
REGISTER_LAST_NAME_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[2]"
REGISTER_MAIL_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[3]"
REGISTER_PASSWORD_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[4]"
REGISTER_PASSWORD_AGAIN_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/input[5]"
REGISTER_SEND_BUTTON_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/button"
REGISTER_CHECK_BOX_CONTACT_XPATH = "/html/body/div[4]/div/div/div/div/div/label[2]/small/input"
REGISTER_CHECK_BOX_MEMBERSHIP_CONTRAT_XPATH = "/html/body/div[4]/div/div/div/div/div/label[3]/small/input"
REGISTER_CHECK_BOX_EMAIL_CONFIRMATION_XPATH = "/html/body/div[4]/div/div/div/div/div/label[4]/small/label[1]/input"
REGISTER_CHECK_BOX_PHONE_CONFIRMATION_XPATH = "/html/body/div[4]/div/div/div/div/div/label[4]/small/label[2]/input"
REGISTER_CHECK_BOX_PHONE_INPUT_XPATH = "//*[@id='phoneNumber']"
IFRAME_XPATH = "//iframe[@title='reCAPTCHA']"
RECAPTCHA_CHECBOX_XPATH = "//span[@id=\'recaptcha-anchor\']/div"
CONTINUE_BUTTON_XPATH = "/html/body/div[4]/div/div/div/div/div/div[3]/button[2]"
REGISTER_SYSTEM_SUCCESSFUL_MESSAGE_XPATH = "//*[@id='__next']/div/main/section/div/div/div/div/span"
REGISTER_MAIL_ERROR_MESSAGE_XPATH = "//*[@id='__next']/div/main/section/div/div/div[1]/div/div/form/p"
PHONE_NUMBER_ERROR_MESSAGE1_XPATH = "/html/body/div[4]/div/div/div/div/div/label[4]/small/p"
REGISTERED_EMAIL_ERROR_MESSAGE = "/html/body/div[1]/div/main/div[2]/div/div[2]"
CHATBOX_XPATH = "//*[@id='exw-conversation-frame-body']/div/div"
PASSWORD_RESET_BUTTON_XPATH = "//p[@class='text-decoration-none text-muted mt-5 d-block']"
HOME_PAGE = "//*[@id='__next']/div/nav/div[1]/ul/li[1]/a"
HOME_PAGE_CONTROLLER = "h3"
MY_PROFILE = "//*[@id='__next']/div/nav/div[1]/ul/li[2]/a"
MY_PROFILE_CONTROLLER = "//span[.='Buse Arslan']"
ASSESSMENTS_CONTROLLER = "//h3[contains(.,'Yetkinliklerini ücretsiz ölç, bilgilerini test et.')]"
ASSESSMENTS = "//*[@id='__next']/div/nav/div[1]/ul/li[3]/a"
CATALOG = "//*[@id='__next']/div/nav/div[1]/ul/li[4]/a"
CATALOG_CONTROLLER = "//span[.='Öğrenmeye başla !']"
CALENDAR = "//*[@id='__next']/div/nav/div[1]/ul/li[5]/a"
CALENDAR_CONTROLLER = ".fc-today-button"
ISTANBUL_CODING = "//*[@id='__next']/div/nav/div[1]/ul/li[6]/a"
ISTANBUL_CODING_CONTROLLER = ".header-text"
MY_COURSES = "lessons-tab"
SHOW_MORE_BUTTON = "//*[@id='lessons-tab-pane']/div/div/div[2]"
GO_ASENKRON_COURSE = "//div[@id='all-lessons-tab-pane']//div[14]//a[.='Eğitime Git']"
ASENKRON_COURSE_CONTROLLER = "[aria-selected='true'] .tabs-nav-title"
ICON_LIKE = "like-button"
ICON_DISLIKE = "//*[@id='main-content']"
VIEW_PERSON = "like-text"
LIKERS_CONTROLLER = ".ant-modal-title"
ABOUT_CONTENT_BUTTON = "//*[@id='rc-tabs-0-tab-about']/div/span"
ABOUT_CONTENT_CONTROLLER = "//strong[.='Başlangıç']"
